# Generated by Django 5.2.6 on 2025-09-28 11:16

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Category = apps.get_model('shop', 'Category')
    Product = apps.get_model('shop', 'Product')

    def unique_slug(model, value, fallback):
        base_slug = slugify(value) if value else ''
        if not base_slug:
            base_slug = fallback
        unique = base_slug
        counter = 1
        while model.objects.filter(slug=unique).exists():
            unique = f"{base_slug}-{counter}"
            counter += 1
        return unique

    for category in Category.objects.all():
        slug = unique_slug(Category, category.name, f"category-{category.pk}")
        Category.objects.filter(pk=category.pk).update(slug=slug)

    for product in Product.objects.select_related('category').all():
        base_value = product.name
        if product.category_id:
            base_value = f"{product.category_id}-{product.name}"
        slug = unique_slug(Product, base_value, f"product-{product.pk}")
        Product.objects.filter(pk=product.pk).update(slug=slug)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
